[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "server"

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200